### Obtener salidas
GET http://127.0.0.1:8000/api/salidas
Accept: application/json 
Authorization: Bearer 1|rmp1VknPHPcGTAkeKPATYttpyj1zf8DU8rZI5ZOI

### Obtener una venta 
GET http://127.0.0.1:8000/api/salidas/1 
Accept: application/json 
Authorization: Bearer 1|rmp1VknPHPcGTAkeKPATYttpyj1zf8DU8rZI5ZOI

### Crear una venta 
POST http://127.0.0.1:8000/api/salidas
Accept: application/json 
Content-Type: application/json 
Authorization: Bearer 1|rmp1VknPHPcGTAkeKPATYttpyj1zf8DU8rZI5ZOI

{
"entrada_id":1 ,"nombre":"Sabritas" ,"salida":500 
}

### Editar venta 
PUT http://127.0.0.1:8000/api/salidas/1 
Accept: application/json 
Content-Type: application/json 
Authorization: Bearer 1|rmp1VknPHPcGTAkeKPATYttpyj1zf8DU8rZI5ZOI

{
"entrada_id":1 ,"nombre":"Bimbo" ,"salida":100
}